version: 1.19.{build}

pull_requests:
  do_not_increment_build_number: true

image: Ubuntu2004

configuration: Release

clone_depth: 1

environment:
  LGC_ENV: DEVELOPMENT
  AWS_DEFAULT_REGION: eu-west-1
  PULUMI_ACCESS_TOKEN:
    secure: 1M5f43O86+9tzzRZM5/0lqD/quSqLs1+5JRRwLHkV7GAXUHYmiURrDTzf7Pa/xwq
  AWS_ACCESS_KEY_ID:
    secure: 87d9QqqeBj+B/oMZcBeFmY0sW4B0lzwBRUuC9fb27r8=
  AWS_SECRET_ACCESS_KEY:
    secure: vsV+r8mOVSG4LC4+3RM7DO8C/5UbrSl9HY2tvCsPrg+ThO/NBrFqoyWGIIY+V1hR
#  PULUMI_DEBUG: true

skip_branch_with_pr: true

cache:
  - packages -> paket.lock
  - paket-files/paket.restore.cached -> paket.lock

nuget:
  disable_publish_on_pr: true
  account_feed: true
  project_feed: true

init:
- sh: |
    curl -fsSL https://get.pulumi.com | sh
    sudo mkdir /publish && sudo chmod 777 /publish
    touch /publish/lambda.zip


before_build:
- sh: |
    export PATH=$PATH:$HOME/.pulumi/bin
    pulumi preview --cwd $APPVEYOR_BUILD_FOLDER/.pulumi --stack devqa

build_script:
- sh: |
    dotnet build pulumi-test.csproj -c Release