version: 1.19.{build}

pull_requests:
  do_not_increment_build_number: true

image: Ubuntu2004

configuration: Release

clone_depth: 1

environment:
  LGC_ENV: DEVELOPMENT
  AWS_DEFAULT_REGION: eu-west-1
  PULUMI_ACCESS_TOKEN:
    secure: qiyholt2kbPh00WxpxkpikM3Aj+XU4okU2+bBBJYt2O0QMRtpmMWj+s+NQee/V77
  AWS_ACCESS_KEY_ID:
    secure: 87d9QqqeBj+B/oMZcBeFmY0sW4B0lzwBRUuC9fb27r8=
  AWS_SECRET_ACCESS_KEY:
    secure: vsV+r8mOVSG4LC4+3RM7DO8C/5UbrSl9HY2tvCsPrg+ThO/NBrFqoyWGIIY+V1hR
#  PULUMI_DEBUG: true

skip_branch_with_pr: true

cache:
  - packages -> paket.lock
  - paket-files/paket.restore.cached -> paket.lock
  - ~/.pulumi/plugins

nuget:
  disable_publish_on_pr: true
  account_feed: true
  project_feed: true

init:
- sh: |
    curl -fsSL https://get.pulumi.com | sh

before_build:
- sh: |
    export PATH=$PATH:$HOME/.pulumi/bin
    pulumi preview --cwd $APPVEYOR_BUILD_FOLDER/.pulumi --stack devqa --refresh --diff

build_script:
- sh: |
    dotnet build -c Release