version: 0.1.{build}

pull_requests:
  do_not_increment_build_number: true

image: Ubuntu2004

configuration: Release

clone_depth: 1

environment:
  LGC_ENV: DEVELOPMENT
  AWS_DEFAULT_REGION: eu-west-1
  PULUMI_ACCESS_TOKEN:
    secure: 1M5f43O86+9tzzRZM5/0lqD/quSqLs1+5JRRwLHkV7GAXUHYmiURrDTzf7Pa/xwq
  AWS_ACCESS_KEY_ID:
    secure: 87d9QqqeBj+B/oMZcBeFmY0sW4B0lzwBRUuC9fb27r8=
  AWS_SECRET_ACCESS_KEY:
    secure: vsV+r8mOVSG4LC4+3RM7DO8C/5UbrSl9HY2tvCsPrg+ThO/NBrFqoyWGIIY+V1hR
  PULUMI_HOME: $(APPVEYOR_BUILD_FOLDER)/.pulumi-home
#  PULUMI_DEBUG: true

skip_branch_with_pr: true

cache:
  - packages -> paket.lock
  - paket-files/paket.restore.cached -> paket.lock
  - .pulumi-home/plugins

artifacts:
- path: Infrastructure.Pulumi\bin\Debug\LetsGetChecked.Infrastructure.Pulumi.*.nupkg


nuget:
  disable_publish_on_pr: true
  account_feed: true
  project_feed: true

dotnet_csproj:
  patch: true
  file: '**/*.csproj;**/*.fsproj;'
  version: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}.0'
  informational_version: '{version}'

init:
- sh: |
    curl -fsSL https://get.pulumi.com | sh

before_build:
- sh: |
    dotnet tool restore
    dotnet paket restore
    dotnet build -c Debug

build_script:
- sh: |
    export PATH=$PATH:$HOME/.pulumi/bin
    pulumi preview --cwd $APPVEYOR_BUILD_FOLDER/.pulumi --stack devqa --refresh --diff


deploy:
- provider: NuGet
  server: https://ci.appveyor.com/nuget/chmely-7fo3yj2gwxt4
  api_key:
    secure: 7YN+iMGUPwOOcxNgWoPht48L8Hs4WWJrPil6UJQULPA=
  skip_symbols: true
    