version: 1.19.{build}

pull_requests:
  do_not_increment_build_number: true

image: Ubuntu2004
#image: Visual Studio 2022

configuration: Release

clone_depth: 1

environment:
  LGC_ENV: DEVELOPMENT
  AWS_DEFAULT_REGION: eu-west-1
  PULUMI_ACCESS_TOKEN:
    secure: 1M5f43O86+9tzzRZM5/0lqD/quSqLs1+5JRRwLHkV7GAXUHYmiURrDTzf7Pa/xwq
  PULUMI_DEBUG: true

skip_branch_with_pr: true

cache:
  - packages -> paket.lock
  - paket-files/paket.restore.cached -> paket.lock

nuget:
  disable_publish_on_pr: true
  account_feed: true
  project_feed: true

init:
- cmd: |
    pwsh -NoProfile -InputFormat None -ExecutionPolicy Bypass -Command "[Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12; iex ((New-Object System.Net.WebClient).DownloadString('https://get.pulumi.com/install.ps1'))"
- sh: |
    curl -fsSL https://get.pulumi.com | sh
    nuget sources add -Name "nuget.org" -Source "https://api.nuget.org/v3/index.json"
    nuget source

before_build:
- cmd: |
    SET "PATH=%PATH%;%USERPROFILE%\.pulumi\bin"
    cd .pulumi
    nuget source
    pulumi stack ls --cwd %APPVEYOR_BUILD_FOLDER%/.pulumi
#    pulumi preview --cwd %APPVEYOR_BUILD_FOLDER%/.pulumi --stack devqa

- sh: |
    export PATH=$PATH:$HOME/.pulumi/bin
    cd .pulumi
    nuget source
    dotnet restore
    pulumi stack ls --cwd $APPVEYOR_BUILD_FOLDER/.pulumi
    pulumi stack select devqa
    pulumi stack
    pulumi preview --cwd $APPVEYOR_BUILD_FOLDER/.pulumi --stack devqa

build_script:
- |
    cd ..
    dotnet build pulumi-test.csproj -c Release