version: 1.19.{build}

pull_requests:
  do_not_increment_build_number: true

image: Ubuntu2004
#image: Visual Studio 2022

configuration: Release

clone_depth: 1

environment:
  LGC_ENV: DEVELOPMENT
  AWS_DEFAULT_REGION: eu-west-1
  PULUMI_ACCESS_TOKEN:
    secure: 1M5f43O86+9tzzRZM5/0lqD/quSqLs1+5JRRwLHkV7GAXUHYmiURrDTzf7Pa/xwq
  PULUMI_DEBUG: true

skip_branch_with_pr: true

cache:
  - packages -> paket.lock
  - paket-files/paket.restore.cached -> paket.lock

nuget:
  disable_publish_on_pr: true
  account_feed: true
  project_feed: true

init:
- sh: |
    curl -fsSL https://get.pulumi.com | sh
    rm -f ~/.nuget/NuGet/NuGet.Config


before_build:
- sh: |
    export PATH=$PATH:$HOME/.pulumi/bin
    cd .pulumi
    nuget source
    pulumi stack ls --cwd $APPVEYOR_BUILD_FOLDER/.pulumi
    pulumi stack select devqa
    pulumi stack
    pulumi preview --cwd $APPVEYOR_BUILD_FOLDER/.pulumi --stack devqa

build_script:
- sh: |
    cd ..
    dotnet build pulumi-test.csproj -c Release